### PR TITLE
Fix gemspec for ruby 2.2

### PR DESCRIPTION
**Pull request by kch**

### CODE REVIEW

**Comment by mattneub** [comment]
Wow, thanks for this! I'm totally out of the ruby loop here. Are we backwards-compatible with this? (Not that it was exactly working as a gem anyway. :) Thx.

**Comment by kch** [comment]
It works with ruby 2.2 and the OS X built-in 2.0.

Didn't test otherwise, but should be fine with 1.9 too.

**Comment by kch** [comment]
i guess you'd need to up the version and release a new gem. the one currently on rubygems fails to install for ruby 2.2.

**Comment by mattneub** [comment]
Good point, but I don't know if we have the right to do that. It's one thing to host a copy of the code and another to claim the kind of authorship that would permit submitting something to rubygems.

**Comment by kch** [comment]
Oh ok. I thought you had taken over ownership for the gem deployment.

Wonder if we can get hamish to cede gem ownership or push the update.

**Comment by mattneub** [comment]
I went ahead and merged - thanks again - maybe you could ask Hamish and you could take over "ownership" on rubygems? He and I have a history, so I don't like to ask him...

**Pull request merged**
